const listGames = [
  {
    id: 1,
    title: 'Star Wars',
    plataformas: 'PlayStation 5, Xbox Series X e Series S, Microsoft Windows',
    generos: 'RPG eletrônico, Jogo eletrônico de furtividade, Ação',
    desenvolvedor: 'Respawn Entertainment, Respawn',
    projetista: 'Jason de Heras, Jeff Magers',
    lancamento: '28 de abril de 2023',
    nota: 9.5,
    aprovacao: '89%',
    imagem: '../img/analise/star-wars.png',
    descricao01: 'Star Wars Jedi: Survivor é um jogo eletrônico desenvolvido pela Respawn Entertainment e publicado pela Electronic Arts. É uma sequência direta de Star Wars Jedi: Fallen Order, lançado em 2019. O jogo foi lançado em 26 de abril de 2023 e está disponível para PlayStation 5, Xbox Series X/S e PC 12.',
    descricao02: 'De acordo com as análises, o jogo é uma evolução do seu antecessor em termos de história, jogabilidade e exploração. O enredo é envolvente e aprimora todos os pontos positivos do seu antecessor, além de corrigir deficiências. O jogo tem uma escala maior e é uma das melhores produções do universo Star Wars.',
    descricao03: 'Se você é fã de Star Wars ou gosta de jogos de aventura, Star Wars Jedi: Survivor é uma ótima escolha.',
    notaJogabilidade: 9.5,
    notaHistoria: 9.5,
    notaGraficos: 9.5,
    notaSom: 9.5,
    notaReplayability: 9.5,
    notaInovacao: 9.5,
    notaDificuldade: 9.5,
  },
  {
    id: 2,
    title: 'Hogwarts Legacy',
    plataformas: 'PlayStation 5, Nintendo Switch, PlayStation 4, Xbox One',
    generos: 'RPG eletrônico, Jogo eletrônico de furtividade, Ação',
    desenvolvedor: 'Avalanche Software',
    projetista: 'James Cabrera',
    lancamento: '10 de fevereiro de 2023',
    nota: 8.7,
    aprovacao: '96%',
    imagem: '../img/analise/hogwarts.png',
    descricao01: 'Hogwarts Legacy é um jogo eletrônico de RPG de ação desenvolvido pela Avalanche Software e publicado pela Warner Bros. Interactive Entertainment sob o selo Portkey Games. O jogo é ambientado no final do século XIX do universo de Harry Potter, um século antes dos eventos narrados nos livros de J.K. Rowling.',
    descricao02: 'O jogador controla um aluno matriculado na Escola de Magia e Bruxaria de Hogwarts que aprende a manejar uma série de habilidades e objetos mágicos. Com a ajuda de colegas e professores, a protagonista embarca em uma jornada para desenterrar um antigo segredo que há muito está escondido no mundo mágico.',
    descricao03: 'Se você é fã de Harry Potter ou gosta de jogos de magia e aventura, Hogwarts Legacy é uma ótima escolha.',
    notaJogabilidade: 8.7,
    notaHistoria: 9.8,
    notaGraficos: 9.3,
    notaSom: 9.4,
    notaReplayability: 8.5,
    notaInovacao: 7.9,
    notaDificuldade: 7.5,
  },
  {
    id: 3,
    title: 'Starfield',
    plataformas: 'Xbox Series X e Series S, Xbox Cloud Gaming, Microsoft Windows',
    generos: 'RPG eletrônico, Jogo eletrônico de furtividade, Ação',
    desenvolvedor: 'Bethesda Game Studios',
    projetista: 'Emil Pagliarulo',
    lancamento: '6 de setembro de 2023',
    nota: 8.7,
    aprovacao: '78%',
    imagem: '../img/analise/starfild.png',
    descricao01: 'Starfield é um jogo eletrônico de RPG de ação e ficção desenvolvido pela Bethesda Game Studios, publicado pela Bethesda Softworks e distribuído pela Microsoft. O jogo foi anunciado pela primeira vez na E3 2018 da Bethesda, sendo descrito como "uma experiência de próxima geração totalmente nova, ambientada em um mundo com temática espacial totalmente novo."',
    descricao02: 'Starfield se passará no ano de 2330 em um pequeno lugar na Via Láctea chamado “The Settled Systems“. Esse sistema solar está localizado a cerca de 50 anos-luz do nosso atual sistema solar. Nosso objetivo no jogo é explorar a área dos Sistemas Colonizados e encontrar novos planetas.',
    descricao03: 'Se você é fã de Espaço Sideral ou gosta de jogos de aventura e futurismo, Starfield é uma ótima escolha.',
    notaJogabilidade: 8.7,
    notaHistoria: 7.8,
    notaGraficos: 8.3,
    notaSom: 7.4,
    notaReplayability: 7.5,
    notaInovacao: 6.9,
    notaDificuldade: 7.5,
  },
  {
    id: 4,
    title: 'Resident Evil 4',
    plataformas: 'PlayStation 5, PlayStation 4, Xbox Series X e Series S, iOS, macOS, Microsoft Windows, Mac OS',
    generos: 'Survival horror, Ação',
    desenvolvedor: 'Capcom',
    projetista: 'Yoshiaki Hirabayashi',
    lancamento: '23 de março de 2023',
    nota: 8.7,
    aprovacao: '96%',
    imagem: '../img/analise/resident-evil-4.png',
    descricao01: 'Resident Evil 4,[nota 1] conhecido no Japão como Biohazard RE:4, é um jogo eletrônico de survival horror desenvolvido e publicado pela Capcom. É um remake de Resident Evil 4, lançado originalmente em 2005 para o Nintendo GameCube.',
    descricao02: 'Assim como no jogo original, o jogador organiza seu inventário com uma "caixa de anexos". Novidade no remake, um sistema de criação permite ao jogador criar itens e munições usando recursos coletados ao longo do jogo. O Mercador retorna, permitindo ao jogador comprar, atualizar e trocar itens.',
    descricao03: 'Se você é fã de Resident Evil ou gosta de jogos de terror e tiro, Resident Evil 4 é uma ótima escolha.',
    notaJogabilidade: 9.5,
    notaHistoria: 9.8,
    notaGraficos: 9.7,
    notaSom: 9.4,
    notaReplayability: 9.5,
    notaInovacao: 8.9,
    notaDificuldade: 8.5,
  },
  {
    id: 3,
    title: 'Ghost of Tsushima',
    plataformas: 'PlayStation 5, PlayStation 4',
    generos: 'RPG eletrônico, Jogo eletrônico de furtividade, Ação',
    desenvolvedor: 'Sucker Punch Productions',
    projetista: 'Darren Bridges',
    lancamento: '17 de julho de 2020',
    nota: 9.5,
    aprovacao: '98%',
    imagem: '../img/analise/star-wars.png',
    descricao01: 'Ghost of Tsushima é um jogo eletrônico de ação-aventura desenvolvido pela Sucker Punch Productions e publicado pela Sony Interactive Entertainment. Ghost of Tsushima foi lançado mundialmente para PlayStation 4 em 17 de julho de 2020, com uma versão expandida e aprimorada para PlayStation 4 e PlayStation 5 estreando em 20 de agosto de 2021.',
    descricao02: 'A história acompanha Jin Sakai, um samurai que precisa proteger a Ilha de Tsushima durante a primeira invasão mongol do Japão.  A jogabilidade apresenta um grande mundo aberto que pode ser explorado a pé ou a cavalo. Ao enfrentar inimigos o jogador pode escolher enfrentá-los diretamente com a katana de Jin ou usar táticas furtivas e assassinar oponentes tornando-se assim o lendário guerreiro conhecido como "o Fantasma".',
    descricao03: 'A Game&Review avalia esse jogo como um dos melhores lançamentos em 2023, chamando atenção por seu combate, narrativa, personagens, interpretações e música',
    notaJogabilidade: 9.5,
    notaHistoria: 9.5,
    notaGraficos: 9.5,
    notaSom: 9.5,
    notaReplayability: 9.5,
    notaInovacao: 9.5,
    notaDificuldade: 9.5,
  }
];

export default listGames;